### ISSUE TITLE
Keep getting errors about missing files

### ISSUE THREAD

**Issue by EightiesPower** [kongzhecn/OMG#1]
When I tried running inference_lora, after following all the instructions in the repo, I first got an error about " no file named model_index.json found in directory", then about "no file named config.json found in directory", then about "no file named diffusion_pytorch_model.bin found in directory", at which point I just renamed my sdxl base model into diffusion_pytorch_model as I wasn't sure which file I was supposed to put there exactly. Now I'm getting the following error: "Can't load tokenizer for './checkpoint/stable-diffusion-xl-base-1.0'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './checkpoint/stable-diffusion-xl-base-1.0' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer."
Can you please specify all the files I need to download to run this? Thanks.

**Comment by kongzhecn** [comment]
You can download the model from 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0' and link it under the 'checkpoint' path. Alternatively, you can directly modify '--pretrained_sdxl_model' to specify the location of your model path.

**Comment by kongzhecn** [comment]
Or if your network can access Hugging Face normally, you can try to set "--pretrained_sdxl_model='stabilityai/stable-diffusion-xl-base-1.0'".

**Comment by EightiesPower** [comment]
> You can download the model from 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0' and link it under the 'checkpoint' path. Alternatively, you can directly modify '--pretrained_sdxl_model' to specify the location of your model path.
I _did have_ sd_xl_base_1.0.safetensors placed in the .\OMG\checkpoint\stable-diffusion-xl-base-1.0 directory, but the code asked for diffusion_pytorch_model.bin before I renamed it.

**Comment by EightiesPower** [comment]
> Or if your network can access Hugging Face normally, you can try to set "--pretrained_sdxl_model='stabilityai/stable-diffusion-xl-base-1.0'".

I did that and got the following error: 

Traceback (most recent call last):
  File "G:\stable diffusion stuff\OMG\inference_lora.py", line 247, in <module>
    pipe, controller, pipe_concepts, pipe_list = build_model_sd(args.pretrained_sdxl_model, args.controlnet_checkpoint, device, prompts_tmp, args.lora_path, width//32, height//32, args.style_lora)
  File "G:\stable diffusion stuff\OMG\inference_lora.py", line 160, in build_model_sd
    pipe_concept.enable_xformers_memory_efficient_attention()
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 2020, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 2046, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 2036, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\modeling_utils.py", line 262, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\modeling_utils.py", line 258, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\modeling_utils.py", line 255, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "G:\miniconda3\envs\OMG\lib\site-packages\diffusers\models\attention_processor.py", line 260, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

And before the error I got this message repeated several times over:

Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.

**Comment by kongzhecn** [comment]
It's advisable not to use the CPU as it can be quite time-consuming. Could you please provide details about your GPU? This project has specific GPU requirements, needing approximately 36GB of memory. A GPU that is too small may not operate effectively.
